import Head from 'next/head'
import {BsFillMoonStarsFill} from 'react-icons/bs';
import {AiFillTwitterCircle, AiFillLinkedin, AiFillYoutube} from 'react-icons/ai';
import Image from 'next/image';
import avi from '../public/avi.png';
import design from '../public/design.png';
import code from '../public/code.png';
import consulting from '../public/consulting.png';
import web1 from '../public/web1.png';
import web2 from '../public/web2.png';
import web3 from '../public/web3.png';
import web4 from '../public/web4.png';
import web5 from '../public/web5.png';
import shop from '../public/shop.jpg';
import photo from '../public/photo.jpg';
import web6 from '../public/web6.png';
import blog from '../public/blog.jpg';
import chat from '../public/chat.jpg';
import social from '../public/social.jpg';
import movie from '../public/movie.jpg';
import { useState, useEffect } from 'react';
import Footer from '../pages/Footer';
import Link from 'next/link';
import tech from '../public/tech_bg.jpg';
import tictactoe from '../public/tictactoe.png';

//import { Inter } from '@next/font/google'
//const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);
  const [time, setTime] = useState();

  useEffect(() =>{
    setInterval(() =>{
      let timeNow = new Date().getTime();
      setTime(timeNow)
    }, 1000)
  });

  let dateNow = new Date().toLocaleString();

  return (
    <div className={darkMode ? 'dark' : ''}>
      <Head>
        <title>Brandon Scott Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='bg-white px-10 md:px-20 lg:px-40 dark:bg-gray-900'>



        <section className='min-h-screen'>
          <nav className='py-10 mb-12 flex justify-between'>
            <h1 className='text-xl font-burtons dark:text-gray-500'>Nice to meet you!</h1>
            <ul className='flex items-center'>
              <li>
                <BsFillMoonStarsFill className='cursur-pointer text-2xl dark:text-gray-500' onClick={() => {setDarkMode(!darkMode)}}/>
              </li>
              <li><a href='#' className='bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8'>Resume</a></li>
            </ul>
          </nav>

          {/* <div className='text-center dark:text-gray-500'>
          <h1 className='text-xl'>Today's Date: {dateNow}</h1>
          </div> */}

          {/* <div className='text-center dark:text-gray-500'>
            <h1 className='text-xl'>{time}</h1>
          </div> */}

          <div className='text-center p-10'>
            <h2 className='text-5xl py-2 text-teal-600 font-medium md:text-6xl'>Brandon Scott</h2>
            <h3 className='text-2xl py-2 md:text-3xl dark:text-gray-500'>React Developer</h3>
            <p className='text-md py-5 leading-8 text-gray-800 md:text-xl max-w-xl mx-auto dark:text-white'>
              Freelancer providing services for programming and design 
              content needs. Join me below and lets get rolling!
            </p>
          </div>
          <div className='text-5xl flex justify-center gap-16 py-3 text-gray-600'>
            <a href='https:www.twitter.com'><AiFillTwitterCircle /> </a>
            <a href='https:www.linkedin.com'> <AiFillLinkedin /> </a>
            <a href='https:www.youtube.com'><AiFillYoutube /></a>
          </div>
          <div className='relative mx-auto mt-20 mb-10 bg-gradient-to-b from-teal-500 rounded-full h-80 w-80 overflow-hidden md:h-100 md:100'>
            <Image src={avi} alt = '' fill objectFit="cover"/>
          </div>
        </section>





        <section>
          <div>
            <h3 className='text-3xl py-1 dark:text-gray-500'>Services I offer</h3>
            <p className='text-md py-2 leading-8 text-gray-800 dark:text-white'>
              Since the beginning of my journey, 
              I have done remote work for
              <span className='text-teal-500'> agencies</span> consulted for
              <span className='text-teal-500'> startups</span> and coloborated
              with talented people to create digital products for both business and
              consumer use.
            </p>
            <p className='text-md py-2 leading-8 text-gray-800 dark:text-white'>
              I offer a wide range of services, including programming and teaching. 
            </p>
          </div>
          
          <div className='lg:flex gap-10 '>
            <div className='text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white'>
              <Image src={design} alt = '' width={100} height={100} className="mx-auto"/>
              <h3 className='text-lg font-medium pt-8 pb-2'>Beautiful Designs</h3>
              <p className='py-2'>
                Creating elegant designs suited for your needs 
                following core design theory.
              </p>
              <h4 className='py-y text-teal-600'>
                Design tools I use
              </h4>
              <p className='text-gray-800 py-1'>Photoshop</p>
              <p className='text-gray-800 py-1'>Illustrator</p>
              <p className='text-gray-800 py-1'>Figma</p>
            </div>

            <div className='text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white'>
              <Image src={code} alt = '' width={100} height={100} className="mx-auto"/>
              <h3 className='text-lg font-medium pt-8 pb-2'>Beautiful Designs</h3>
              <p className='py-2'>
                Creating elegant designs suited for your needs 
                following core design theory.
              </p>
              <h4 className='py-y text-teal-600'>
                Design tools I use
              </h4>
              <p className='text-gray-800 py-1'>Photoshop</p>
              <p className='text-gray-800 py-1'>Illustrator</p>
              <p className='text-gray-800 py-1'>Figma</p>
            </div>

            <div className='text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white'>
              <Image src={consulting} alt='' width={100} height={100} className="mx-auto"/>
              <h3 className='text-lg font-medium pt-8 pb-2'>Beautiful Designs</h3>
              <p className='py-2'>
                Creating elegant designs suited for your needs 
                following core design theory.
              </p>
              <h4 className='py-y text-teal-600'>
                Design tools I use
              </h4>
              <p className='text-gray-800 py-1'>Photoshop</p>
              <p className='text-gray-800 py-1'>Illustrator</p>
              <p className='text-gray-800 py-1'>Figma</p>
            </div>
          </div>
        </section>





        <section>
          <div>
            <h3 className='text-3xl py-1 dark:text-gray-500'>Portfolio</h3>
            <p className='text-md py-2 leading-8 text-gray-800 dark:text-white'>
              Since the beginning of my journey, 
              I have done remote work for
              <span className='text-teal-500'> agencies</span> consulted for
              <span className='text-teal-500'> startups</span> and coloborated
              with talented people to create digital products for both business and
              consumer use.
            </p>
            <p className='text-md py-2 leading-8 text-gray-800 dark:text-white'>
              I offer a wide range of services, including programming and teaching. 
            </p>
          </div>


          <div className='flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap'>
            <Link href='../../cms_blog/pages/index.tsx' className='basis-1/3 flex-1'>
              <div className='basis-1/3 flex-1'>
                <Image alt='' src={blog} className="rounded-lg object-cover" width={"100%"} height={"100%"} layout="responsive"/>
              </div>
            </Link>



            <Link href='#' className='basis-1/3 flex-1'><div className='basis-1/3 flex-1'><Image src={chat} alt='' className="rounded-lg object-cover" width={"100%"} height={"100%"} layout="responsive" /></div></Link>
            <Link href='#' className='basis-1/3 flex-1'><div className='basis-1/3 flex-1'><Image src={social} alt='' className="rounded-lg object-cover" width={"100%"} height={"100%"} layout="responsive" /></div></Link>
            <Link href='#' className='basis-1/3 flex-1'><div className='basis-1/3 flex-1'><Image src={movie} alt='' className="rounded-lg object-cover" width={"100%"} height={"100%"} layout="responsive" /></div></Link>
            <Link href='#' className='basis-1/3 flex-1'><div className='basis-1/3 flex-1'><Image src={shop} alt='' className="rounded-lg object-cover" width={"100%"} height={"100%"} layout="responsive" /></div></Link>
            <Link href='#' className='basis-1/3 flex-1'><div className='basis-1/3 flex-1'><Image src={photo} alt='' className="rounded-lg object-cover" width={"100%"} height={"100%"} layout="responsive" /></div></Link>
            <Link href='#' className='basis-1/3 flex-1'><div className='basis-1/3 flex-1'><Image src={tictactoe} alt='' className="rounded-lg object-cover" width={"100%"} height={"100%"} layout="responsive" /></div></Link>
            <Link href='#' className='basis-1/3 flex-1'><div className='basis-1/3 flex-1'><Image src={tictactoe} alt='' className="rounded-lg object-cover" width={"100%"} height={"100%"} layout="responsive" /></div></Link>
          </div>
        </section>
      </main>
      <Footer />
    </div>
  )
}
